
package client;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "DDOServerService", targetNamespace = "http://server/", wsdlLocation = "http://localhost:3456/ws/Dollard?wsdl")
public class DDOServerService
    extends Service
{

    private final static URL DDOSERVERSERVICE_WSDL_LOCATION;
    private final static WebServiceException DDOSERVERSERVICE_EXCEPTION;
    private final static QName DDOSERVERSERVICE_QNAME = new QName("http://server/", "DDOServerService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:3456/ws/Dollard?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        DDOSERVERSERVICE_WSDL_LOCATION = url;
        DDOSERVERSERVICE_EXCEPTION = e;
    }

    public DDOServerService() {
        super(__getWsdlLocation(), DDOSERVERSERVICE_QNAME);
    }

    public DDOServerService(WebServiceFeature... features) {
        super(__getWsdlLocation(), DDOSERVERSERVICE_QNAME, features);
    }

    public DDOServerService(URL wsdlLocation) {
        super(wsdlLocation, DDOSERVERSERVICE_QNAME);
    }

    public DDOServerService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, DDOSERVERSERVICE_QNAME, features);
    }

    public DDOServerService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public DDOServerService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns CenterServer
     */
    @WebEndpoint(name = "DDOServerPort")
    public CenterServer getDDOServerPort() {
        return super.getPort(new QName("http://server/", "DDOServerPort"), CenterServer.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CenterServer
     */
    @WebEndpoint(name = "DDOServerPort")
    public CenterServer getDDOServerPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://server/", "DDOServerPort"), CenterServer.class, features);
    }

    private static URL __getWsdlLocation() {
        if (DDOSERVERSERVICE_EXCEPTION!= null) {
            throw DDOSERVERSERVICE_EXCEPTION;
        }
        return DDOSERVERSERVICE_WSDL_LOCATION;
    }

}
