
package client;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "LVLServerService", targetNamespace = "http://server/", wsdlLocation = "http://localhost:2345/ws/Laval?wsdl")
public class LVLServerService
    extends Service
{

    private final static URL LVLSERVERSERVICE_WSDL_LOCATION;
    private final static WebServiceException LVLSERVERSERVICE_EXCEPTION;
    private final static QName LVLSERVERSERVICE_QNAME = new QName("http://server/", "LVLServerService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:2345/ws/Laval?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        LVLSERVERSERVICE_WSDL_LOCATION = url;
        LVLSERVERSERVICE_EXCEPTION = e;
    }

    public LVLServerService() {
        super(__getWsdlLocation(), LVLSERVERSERVICE_QNAME);
    }

    public LVLServerService(WebServiceFeature... features) {
        super(__getWsdlLocation(), LVLSERVERSERVICE_QNAME, features);
    }

    public LVLServerService(URL wsdlLocation) {
        super(wsdlLocation, LVLSERVERSERVICE_QNAME);
    }

    public LVLServerService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, LVLSERVERSERVICE_QNAME, features);
    }

    public LVLServerService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public LVLServerService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns CenterServer
     */
    @WebEndpoint(name = "LVLServerPort")
    public CenterServer getLVLServerPort() {
        return super.getPort(new QName("http://server/", "LVLServerPort"), CenterServer.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CenterServer
     */
    @WebEndpoint(name = "LVLServerPort")
    public CenterServer getLVLServerPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://server/", "LVLServerPort"), CenterServer.class, features);
    }

    private static URL __getWsdlLocation() {
        if (LVLSERVERSERVICE_EXCEPTION!= null) {
            throw LVLSERVERSERVICE_EXCEPTION;
        }
        return LVLSERVERSERVICE_WSDL_LOCATION;
    }

}
