
package client;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "MTLServerService", targetNamespace = "http://server/", wsdlLocation = "http://localhost:1234/ws/Montreal?wsdl")
public class MTLServerService
    extends Service
{

    private final static URL MTLSERVERSERVICE_WSDL_LOCATION;
    private final static WebServiceException MTLSERVERSERVICE_EXCEPTION;
    private final static QName MTLSERVERSERVICE_QNAME = new QName("http://server/", "MTLServerService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:1234/ws/Montreal?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        MTLSERVERSERVICE_WSDL_LOCATION = url;
        MTLSERVERSERVICE_EXCEPTION = e;
    }

    public MTLServerService() {
        super(__getWsdlLocation(), MTLSERVERSERVICE_QNAME);
    }

    public MTLServerService(WebServiceFeature... features) {
        super(__getWsdlLocation(), MTLSERVERSERVICE_QNAME, features);
    }

    public MTLServerService(URL wsdlLocation) {
        super(wsdlLocation, MTLSERVERSERVICE_QNAME);
    }

    public MTLServerService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, MTLSERVERSERVICE_QNAME, features);
    }

    public MTLServerService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public MTLServerService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns CenterServer
     */
    @WebEndpoint(name = "MTLServerPort")
    public CenterServer getMTLServerPort() {
        return super.getPort(new QName("http://server/", "MTLServerPort"), CenterServer.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CenterServer
     */
    @WebEndpoint(name = "MTLServerPort")
    public CenterServer getMTLServerPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://server/", "MTLServerPort"), CenterServer.class, features);
    }

    private static URL __getWsdlLocation() {
        if (MTLSERVERSERVICE_EXCEPTION!= null) {
            throw MTLSERVERSERVICE_EXCEPTION;
        }
        return MTLSERVERSERVICE_WSDL_LOCATION;
    }

}
